stages:
  prepare_data:
    cmd: python prepare_data.py ${data.output_folder}
    deps:
    - prepare_data.py
    outs:
    - ${data.output_folder}
  train:
    cmd: python main.py
    deps:
    - ${data.output_folder}
    - main.py
    - modeling/diffusion.py
    - modeling/training.py
    - modeling/unet.py
    - conf/config.yaml
    - conf/model.yaml
    - conf/training.yaml
    - conf/data.yaml
    - conf/optimizer/adam.yaml
    - conf/optimizer/sgd.yaml
    outs:
    - ${training.output_file}