optimizer:
  type: Adam
  lr: 1.0e-05
model:
  in_channels: 3
  out_channels: 3
  betas:
  - 0.0001
  - 0.02
  num_timesteps: 1000
  hidden_size: 8
data:
  num_workers: 4
  output_folder: cifar10
training:
  batch_size: 256
  num_epochs: 5
  device: cuda
  augmentations: false
  output_file: model.pt
